modLoader="javafml"
loaderVersion="[36,)"
license="license.txt"
issueTrackerURL="https://github.com/InfinityRaider/NinjaGear/issues/"

[[mods]]
modId="ninja_gear"
version="1.16.5-2.0.4"
displayName="Ninja Gear"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/ninjagear/files"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ninjagear"
logoFile="logo.png"
authors="InfinityRaider"
description='''
Become a ninja, sneak around in the darkness, scale walls and explore new forms of combat.
'''

[[dependencies.ninja_gear]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ninja_gear]]
    modId="infinitylib"
    mandatory=true
    versionRange="[1.16.5-2.0.3,)"
    ordering="AFTER"
    side="BOTH"